version: "3"

services:

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: hse
    networks:
      - hsenet


  app:
    image: hse/test:1.0.2
    environment:
      DB_PORT: 5432
      DB_DB: hse
      DB_USER: user
      DB_PASSWORD: 123
      DB_HOST: db
    command: ["./tools/wait.sh", "db:5432", "--", "node", "."]
    ports:
      - 8081:8080
    networks:
      - hsenet

networks:
  hsenet: